linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - copyloopvar  # Replacement for exportloopref
    - gocyclo
    - misspell
  disable:
    - errcheck  # Temporarily disable error checking until all code is updated

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck  # Don't enforce error checking in test files

run:
  timeout: 5m
